




// // 'use client';
// // import { useAssessmentStore } from '../store/useAssessmentStore';

// // export default function ResultsView() {
// //   const store = useAssessmentStore();
// //   const paper = store.generatedPaper;

// //   if (!paper) return null;

// //   return (
// //     <div className="bg-white rounded-2xl p-8 max-w-4xl mx-auto shadow-sm border border-gray-100">
// //       <div className="flex justify-between items-start mb-8 border-b pb-6">
// //         <div>
// //           <h2 className="text-3xl font-bold text-gray-900 mb-2">{paper.topic}</h2>
// //           <p className="text-gray-500">Generated by VedaAI</p>
// //         </div>
// //         <div className="text-right">
// //           <p className="text-sm font-bold text-gray-800 bg-gray-100 px-3 py-1 rounded-lg inline-block mb-1">
// //             Total Marks: {paper.totalMarks}
// //           </p>
// //           <p className="text-sm text-gray-500 block">Questions: {paper.numQuestions}</p>
// //         </div>
// //       </div>

// //       <div className="space-y-10">
// //         {paper.paperStructure?.sections?.map((section: any, sIndex: number) => (
// //           <div key={sIndex} className="bg-gray-50/50 rounded-xl p-6 border border-gray-100">
// //             <h3 className="text-xl font-bold text-gray-800 mb-1">{section.title}</h3>
// //             <p className="text-sm text-gray-500 italic mb-6">{section.instruction}</p>
            
// //             <div className="space-y-6">
// //               {section.questions?.map((q: any, qIndex: number) => (
// //                 <div key={qIndex} className="flex gap-4">
// //                   <span className="font-bold text-gray-400 mt-0.5">Q{qIndex + 1}.</span>
// //                   <div className="flex-1">
// //                     <p className="text-gray-800 font-medium leading-relaxed">{q.text}</p>
// //                     <div className="flex gap-3 mt-3">
// //                       <span className={`text-xs px-2 py-1 rounded-md font-medium ${
// //                         q.difficulty === 'Easy' ? 'bg-green-100 text-green-700' :
// //                         q.difficulty === 'Moderate' ? 'bg-yellow-100 text-yellow-700' :
// //                         'bg-red-100 text-red-700'
// //                       }`}>
// //                         {q.difficulty}
// //                       </span>
// //                     </div>
// //                   </div>
// //                   <div className="font-bold text-gray-900 bg-white border border-gray-200 px-3 py-1 h-fit rounded-lg shadow-sm">
// //                     {q.marks} {q.marks === 1 ? 'mark' : 'marks'}
// //                   </div>
// //                 </div>
// //               ))}
// //             </div>
// //           </div>
// //         ))}
// //       </div>

// //       <div className="mt-10 pt-6 border-t flex justify-between">
// //         <button 
// //           onClick={() => store.setGeneratedPaper(null)} 
// //           className="text-gray-500 hover:text-gray-900 font-medium text-sm transition"
// //         >
// //           ← Create Another
// //         </button>
// //         <button className="bg-orange-600 text-white px-6 py-2.5 rounded-full text-sm font-bold hover:bg-orange-700 transition shadow-sm">
// //           Export as PDF
// //         </button>
// //       </div>
// //     </div>
// //   );
// // }






// 'use client';
// import { useRef, useState } from 'react';
// import { useAssessmentStore } from '../store/useAssessmentStore';
// import PrintableExam from './PrintableExam';
// import jsPDF from 'jspdf';
// import html2canvas from 'html2canvas';

// export default function ResultsView() {
//   const store = useAssessmentStore();
//   const paper = store.generatedPaper;
//   const printRef = useRef<HTMLDivElement>(null);
//   const [isExporting, setIsExporting] = useState(false);

//   if (!paper) return null;

//   const handleExportPDF = async () => {
//     if (!printRef.current) return;
//     setIsExporting(true);

//     try {
//       const canvas = await html2canvas(printRef.current, { scale: 2 });
//       const imgData = canvas.toDataURL('image/png');
      
//       const pdf = new jsPDF({
//         orientation: 'portrait',
//         unit: 'px',
//         format: 'a4',
//       });

//       const pdfWidth = pdf.internal.pageSize.getWidth();
//       const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

//       pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
//       pdf.save(`${paper.topic.replace(/\s+/g, '_')}_Exam.pdf`);
//     } catch (error) {
//       console.error('Error generating PDF', error);
//       alert('Failed to generate PDF. Please try again.');
//     } finally {
//       setIsExporting(false);
//     }
//   };

//   return (
//     <>
//       {/* Hidden printable component */}
//       <PrintableExam ref={printRef} paper={paper} />

//       {/* Standard Web View */}
//       <div className="bg-white rounded-2xl p-8 max-w-4xl mx-auto shadow-sm border border-gray-100">
//         <div className="flex justify-between items-start mb-8 border-b pb-6">
//           <div>
//             <h2 className="text-3xl font-bold text-gray-900 mb-2">{paper.topic}</h2>
//             <p className="text-gray-500">Generated by VedaAI</p>
//           </div>
//           <div className="text-right">
//             <p className="text-sm font-bold text-gray-800 bg-gray-100 px-3 py-1 rounded-lg inline-block mb-1">
//               Total Marks: {paper.totalMarks}
//             </p>
//             <p className="text-sm text-gray-500 block">Questions: {paper.numQuestions}</p>
//           </div>
//         </div>

//         <div className="space-y-10">
//           {paper.paperStructure?.sections?.map((section: any, sIndex: number) => (
//             <div key={sIndex} className="bg-gray-50/50 rounded-xl p-6 border border-gray-100">
//               <h3 className="text-xl font-bold text-gray-800 mb-1">{section.title}</h3>
//               <p className="text-sm text-gray-500 italic mb-6">{section.instruction}</p>
              
//               <div className="space-y-6">
//                 {section.questions?.map((q: any, qIndex: number) => (
//                   <div key={qIndex} className="flex gap-4">
//                     <span className="font-bold text-gray-400 mt-0.5">Q{qIndex + 1}.</span>
//                     <div className="flex-1">
//                       <p className="text-gray-800 font-medium leading-relaxed">{q.text}</p>
//                       <div className="flex gap-3 mt-3">
//                         <span className={`text-xs px-2 py-1 rounded-md font-medium ${
//                           q.difficulty === 'Easy' ? 'bg-green-100 text-green-700' :
//                           q.difficulty === 'Moderate' ? 'bg-yellow-100 text-yellow-700' :
//                           'bg-red-100 text-red-700'
//                         }`}>
//                           {q.difficulty}
//                         </span>
//                       </div>
//                     </div>
//                     <div className="font-bold text-gray-900 bg-white border border-gray-200 px-3 py-1 h-fit rounded-lg shadow-sm">
//                       {q.marks} {q.marks === 1 ? 'mark' : 'marks'}
//                     </div>
//                   </div>
//                 ))}
//               </div>
//             </div>
//           ))}
//         </div>

//         <div className="mt-10 pt-6 border-t flex justify-between items-center">
//           <button 
//             onClick={() => store.setGeneratedPaper(null)} 
//             className="text-gray-500 hover:text-gray-900 font-medium text-sm transition"
//           >
//             ← Create Another
//           </button>
          
//           <button 
//             onClick={handleExportPDF}
//             disabled={isExporting}
//             className="bg-orange-600 text-white px-6 py-2.5 rounded-full text-sm font-bold hover:bg-orange-700 transition shadow-sm disabled:opacity-50 flex items-center gap-2"
//           >
//             {isExporting ? 'Generating PDF...' : 'Export as PDF'}
//           </button>
//         </div>
//       </div>
//     </>
//   );
// }




'use client';
import { useRef, useState } from 'react';
import { useAssessmentStore } from '../store/useAssessmentStore';
import PrintableExam from './PrintableExam';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function ResultsView() {
  const store = useAssessmentStore();
  const paper = store.generatedPaper;
  const printRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);

  if (!paper) return null;

  // --- REGENERATE LOGIC ---
  const handleRegenerate = async () => {
    // 1. Calculate totals from the store
    const totalQuestions = store.questionTypes.reduce((acc, curr) => acc + curr.count, 0);
    const totalMarks = store.questionTypes.reduce((acc, curr) => acc + (curr.count * curr.marks), 0);

    // 2. Clear the current paper and show the loader
    store.setGeneratedPaper(null);
    store.setGenerating(true);

    // 3. Send the request back to the backend
    try {
      const response = await fetch('http://localhost:8080/api/assignments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: "Science Exam", 
          dueDate: store.dueDate,
          numQuestions: totalQuestions,
          totalMarks: totalMarks,
          instructions: store.additionalInfo
        })
      });
      const data = await response.json();
      
      // Save the new ID so the WebSocket in CreateAssignmentForm can pick it up
      store.setGenerating(true, data.assignmentId); 
    } catch (error) {
      console.error('Regeneration failed', error);
      store.setGenerating(false);
    }
  };

  // --- PDF EXPORT LOGIC ---
  const handleExportPDF = async () => {
    if (!printRef.current) return;
    setIsExporting(true);

    try {
      const canvas = await html2canvas(printRef.current, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' });
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`${paper.topic.replace(/\s+/g, '_')}_Exam.pdf`);
    } catch (error) {
      console.error('Error generating PDF', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <>
      <PrintableExam ref={printRef} paper={paper} />

      <div className="bg-white rounded-2xl p-8 max-w-4xl mx-auto shadow-sm border border-gray-100">
        <div className="flex justify-between items-start mb-8 border-b pb-6">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">{paper.topic}</h2>
            <p className="text-gray-500">Generated by VedaAI</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-gray-800 bg-gray-100 px-3 py-1 rounded-lg inline-block mb-1">
              Total Marks: {paper.totalMarks}
            </p>
            <p className="text-sm text-gray-500 block">Questions: {paper.numQuestions}</p>
          </div>
        </div>

        {/* STUDENT INFO SECTION (Added per rubric) */}
        <div className="flex gap-6 mb-10 p-6 bg-gray-50/50 rounded-xl border border-gray-100">
          <div className="flex-1">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Student Name</label>
            <div className="border-b-2 border-gray-300 w-full h-8"></div>
          </div>
          <div className="w-32">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Roll Number</label>
            <div className="border-b-2 border-gray-300 w-full h-8"></div>
          </div>
          <div className="w-32">
            <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Section</label>
            <div className="border-b-2 border-gray-300 w-full h-8"></div>
          </div>
        </div>

        <div className="space-y-10">
          {paper.paperStructure?.sections?.map((section: any, sIndex: number) => (
            <div key={sIndex} className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="bg-gray-50 border-b border-gray-200 px-6 py-4">
                <h3 className="text-lg font-bold text-gray-800">{section.title}</h3>
                <p className="text-sm text-gray-500 italic mt-1">{section.instruction}</p>
              </div>
              
              <div className="p-6 space-y-6">
                {section.questions?.map((q: any, qIndex: number) => (
                  <div key={qIndex} className="flex gap-4">
                    <span className="font-bold text-gray-400 mt-0.5">Q{qIndex + 1}.</span>
                    <div className="flex-1">
                      <p className="text-gray-800 font-medium leading-relaxed">{q.text}</p>
                      <div className="flex gap-3 mt-3">
                        <span className={`text-xs px-2.5 py-1 rounded-md font-bold ${
                          q.difficulty === 'Easy' ? 'bg-green-100 text-green-700' :
                          q.difficulty === 'Moderate' ? 'bg-yellow-100 text-yellow-700' :
                          'bg-red-100 text-red-700'
                        }`}>
                          {q.difficulty}
                        </span>
                      </div>
                    </div>
                    <div className="font-bold text-gray-900 bg-gray-50 border border-gray-200 px-3 py-1 h-fit rounded-lg shadow-sm">
                      {q.marks} {q.marks === 1 ? 'mark' : 'marks'}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* ACTION BAR (Added Regenerate Button per rubric) */}
        <div className="mt-10 pt-6 border-t flex justify-between items-center bg-white sticky bottom-0">
          <button 
            onClick={() => store.setGeneratedPaper(null)} 
            className="text-gray-500 hover:text-gray-900 font-medium text-sm transition px-4 py-2"
          >
            ← Create New
          </button>
          
          <div className="flex gap-4">
            <button 
              onClick={handleRegenerate}
              className="bg-white text-gray-800 border border-gray-300 px-6 py-2.5 rounded-full text-sm font-bold hover:bg-gray-50 transition shadow-sm flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path></svg>
              Regenerate
            </button>

            <button 
              onClick={handleExportPDF}
              disabled={isExporting}
              className="bg-orange-600 text-white px-6 py-2.5 rounded-full text-sm font-bold hover:bg-orange-700 transition shadow-sm disabled:opacity-50 flex items-center gap-2"
            >
              {isExporting ? 'Generating PDF...' : 'Export as PDF'}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}